repos:
  - repo: local
    hooks:
      - id: docgen-inject
        name: Inject docstrings
        entry: python -m docgen.injector.docstring_injector
        language: system
        pass_filenames: false

      - id: docgen-check
        name: Validate documentation
        entry: python -m docgen.check_docs
        language: system
        pass_filenames: false